
#include <stdio.h>
#include <signal.h>

void handle_signal(int signum) {
    printf("Received signal %d\n", signum);
}

int main() {
    // Register the signal handler for SIGINT (usually generated by pressing Ctrl+C)
    signal(SIGINT, handle_signal);
    
    printf("Waiting for a signal...\n");
    while (1) {}  // Infinite loop to keep the program running indefinitely
    return 0;
}
