
#include <stdio.h>

int main() {
    // Testing C language extensions or features not part of standard C
    _Pragma("GCC diagnostic push")
    _Pragma("GCC diagnostic ignored \"-Wpedantic\"")
    int i = 0;
    int array[10];
    for (i = 0; i < 10; ++i) {
        array[i] = i * 2;
    }
    _Pragma("GCC diagnostic pop")

    // Printing specific output based on that feature
    printf("Array of integers with values generated by C language extension: ");
    for (i = 0; i < 10; ++i) {
        printf("%d ", array[i]);
    }
    printf("\n");

    return 0;
}
